version: '3.8'

services:
    demo:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.demo-dev
        ports:
            - '3000:3000'
        command: sam local start-api -t "${PWD}/apps/demo-lambda/sam-template.yaml" -v "${PWD}/.aws-sam/build" --host=0.0.0.0 --container-host=host.docker.internal --container-host-interface=127.0.0.1 --invoke-image=public.ecr.aws/lambda/nodejs:20-rapid-x86_64 --warm-containers=eager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${PWD}/apps/demo-lambda/build:${PWD}${PWD}/apps/demo-lambda/build:ro
            - ${PWD}/apps/demo-lambda/node_modules
            - ${PWD}/node_modules
        environment:
            SAM_CLI_TELEMETRY: 0
            SAM_CLI_CONTAINER_CONNECTION_TIMEOUT: 30
            sam_local_environment: 'true'

networks:
    dashboard_network:
        driver: bridge
