FROM node:20.11.1 as base

RUN npm i -g pnpm@8.15.4

FROM public.ecr.aws/docker/library/docker

# Install NodeJS & NPM & PNPM to image
COPY --from=base /usr/local/bin /usr/local/bin
COPY --from=base /usr/local/lib/node_modules /usr/local/lib/node_modules

RUN ln -s /usr/local/bin/node /usr/bin/node
RUN ln -s /usr/local/bin/npm /usr/bin/npm
RUN ln -s /usr/local/bin/pnpm /usr/bin/pnpm

ENV PATH "/usr/local/bin:${PATH}"

# * https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana
ENV PIP_BREAK_SYSTEM_PACKAGES 1

RUN apk update && \
    apk add gcc py-pip python3-dev libffi-dev musl-dev && \
    pip install --upgrade pip setuptools wheel && \
    pip install --upgrade aws-sam-cli

WORKDIR /var/opt

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/demo-lambda/package.json ./apps/demo-lambda/

RUN pnpm i -w
RUN pnpm --filter demo-lambda i

COPY ./tsconfig.base.json ./
COPY ./apps/demo-lambda/ ./apps/demo-lambda/

ENTRYPOINT []
CMD ["/bin/bash"]